language: ruby
rvm:
  - 1.9.3
notifications:
  email:
    - sebastian.graessl@gmail.com
before_script:
  - rake config/initializers/session_store.rb
  - mysql -e 'create database mephisto_test'
  - RAILS_ENV=test bundle exec rake db:schema:load db:migrate
