language: ruby
rvm:
  - 1.8.7
  - ree
notifications:
  email:
    - sebastian.graessl@gmail.com
script:
	- time bundle exec rake
before_script:
  - rake config/initializers/session_store.rb
  - mysql -e 'create database mephisto_test'
  - RAILS_ENV=test bundle exec rake --trace db:schema:load db:migrate
