branches:
  only:
    - master
notifications:
  email:
    - sebastian@validcode.me
before_script: 'cp config/database.example.yml config/database.yml && rake config/initializers/session_store.rb && rake db:test:prepare'