development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: mysql2
  host: localhost
  database: mephisto_test
  user: root

production:
  adapter: mysql2
  host: localhost
  database: mephisto_production
  user: root
