development:
  adapter: mysql2
  host: localhost
  database: mephisto_development
  user: root

test:
  adapter: sqlite3
  database: db/test.sqlite3


production:
  adapter: sqlite3
  database: db/production.sqlite3
